# Generated by Django 3.2.8 on 2021-10-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='workphotos',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
