# Generated by Django 3.2.8 on 2021-10-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_workphotos_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Пости'},
        ),
    ]
