# Generated by Django 3.0 on 2021-11-07 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211105_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=255, unique=True, verbose_name='Url'),
        ),
    ]
