# Generated by Django 3.0 on 2021-11-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211127_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='time',
            field=models.TimeField(),
        ),
    ]
